### ISSUE TITLE
Drop netstandard and target net452 only?

### ISSUE THREAD

**Issue by JohanLarsson** [JohanLarsson/Gu.Roslyn.Asserts#37]

**Comment by JohanLarsson** [comment]
1.x versions will be net452 & roslyn 1.x.

**Comment by jnm2** [comment]
I currently target my analyzer test projects `net47;netcoreapp2.0`. Would you be willing to multitarget the 2.x?

**Comment by JohanLarsson** [comment]
Yes we should try to get it to work, I don't remember what made me give up on multitargeting. Why do you multitarget the test projects btw?
